apiVersion: apps/v1
kind: Deployment
metadata:
  name: tip-calculator
spec:
  selector:
    matchLabels:
      app: tip-calculator
  template:
    metadata:
      labels:
        app: tip-calculator
    spec:
      containers:
        - name: tip-calculator
          image: gcardenasdev/tip-calculator
          ports:
            - containerPort: 3000